export const statsData = {
  students: 1247,
  courses: 24,
  rating: 4.8,
  revenue: 12847,
};

export const activitiesData = [
  { course: "React Fundamentals", students: 45, status: "active" },
  { course: "Advanced JavaScript", students: 32, status: "active" },
  { course: "Node.js Backend", students: 28, status: "draft" },
  { course: "Database Design", students: 67, status: "active" },
];

export const coursesData = [
  {
    title: "React Fundamentals",
    students: 245,
    rating: 4.8,
    status: "Published",
    image:
      "https://images.pexels.com/photos/11035380/pexels-photo-11035380.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
  {
    title: "Advanced JavaScript",
    students: 189,
    rating: 4.7,
    status: "Published",
    image:
      "https://images.pexels.com/photos/270348/pexels-photo-270348.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
  {
    title: "Node.js Backend Development",
    students: 156,
    rating: 4.9,
    status: "Published",
  },
  {
    title: "Database Design Principles",
    students: 0,
    rating: 0,
    status: "Draft",
    image:
      "https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
];

export const learnersData = [
  {
    name: "Sarah Johnson",
    email: "sarah@example.com",
    courses: 3,
    progress: 85,
    lastActive: "2 hours ago",
  },
  {
    name: "Mike Chen",
    email: "mike@example.com",
    courses: 2,
    progress: 92,
    lastActive: "1 day ago",
  },
  {
    name: "Emma Davis",
    email: "emma@example.com",
    courses: 4,
    progress: 67,
    lastActive: "3 hours ago",
  },
  {
    name: "Alex Wilson",
    email: "alex@example.com",
    courses: 1,
    progress: 45,
    lastActive: "5 days ago",
  },
  {
    name: "Lisa Brown",
    email: "lisa@example.com",
    courses: 2,
    progress: 78,
    lastActive: "1 hour ago",
  },
];

export const conversations = [
  {
    id: 1,
    name: "Sarah Johnson",
    lastMessage: "Question about React hooks...",
    time: "2 min ago",
    messages: [
      {
        id: 1,
        sender: "Sarah Johnson",
        text: "Question about React hooks...",
        time: "2 min ago",
        isRead: false,
      },
      {
        id: 2,
        sender: "Me",
        text: "Sure, what's your issue?",
        time: "15 min ago",
        isRead: true,
      },
      {
        id: 3,
        sender: "Sarah Johnson",
        text: "Question about React hooks...",
        time: "1 hour ago",
        isRead: false,
      },
      {
        id: 4,
        sender: "Me",
        text: "Sure, what's your issue?",
        time: "2 hours ago",
        isRead: true,
      },
    ],
  },
  {
    id: 2,
    name: "Mike Chen",
    lastMessage: "Assignment submission help...",
    time: "15 min ago",
    messages: [
      {
        id: 1,
        sender: "Mike Chen",
        text: "Assignment submission help...",
        isRead: false,
      },
    ],
  },
  {
    id: 3,
    name: "Emma Davis",
    lastMessage: "Course completion certificate...",
    time: "1 hour ago",
    messages: [
      {
        id: 1,
        sender: "Emma Davis",
        text: "Course completion certificate...",
        isRead: true,
      },
    ],
  },
];

// Mock data for enrolled courses
export const enrolledCourses = [
  {
    key: "1",
    id: "CRS001",
    title: "Advanced React Development",
    instructor: "Dr. Sarah Chen",
    category: "Programming",
    level: "Advanced",
    progress: 65,
    status: "in-progress",
    rating: 4.9,
    totalLessons: 24,
    completedLessons: 16,
    duration: "12 hours",
    lastAccessed: "2024-01-20",
    thumbnail: null,
  },
  {
    key: "2",
    id: "CRS002",
    title: "Machine Learning Fundamentals",
    instructor: "Prof. Michael Rodriguez",
    category: "Data Science",
    level: "Intermediate",
    progress: 100,
    status: "completed",
    rating: 4.8,
    totalLessons: 32,
    completedLessons: 32,
    duration: "18 hours",
    lastAccessed: "2024-01-15",
    thumbnail: null,
  },
  {
    key: "3",
    id: "CRS003",
    title: "Digital Marketing Strategy",
    instructor: "Lisa Thompson",
    category: "Marketing",
    level: "Beginner",
    progress: 0,
    status: "saved",
    rating: 4.7,
    totalLessons: 16,
    completedLessons: 0,
    duration: "8 hours",
    lastAccessed: "Never",
    thumbnail: null,
  },
  {
    key: "4",
    id: "CRS004",
    title: "Python for Beginners",
    instructor: "David Park",
    category: "Programming",
    level: "Beginner",
    progress: 30,
    status: "in-progress",
    rating: 4.6,
    totalLessons: 20,
    completedLessons: 6,
    duration: "10 hours",
    lastAccessed: "2024-01-18",
    thumbnail: null,
  },
];

// Mock data for all available courses
export const allCourses = [
  {
    key: "1",
    id: "CRS001",
    title: "Advanced React Development",
    instructor: "Dr. Sarah Chen",
    category: "Programming",
    level: "Advanced",
    rating: 4.9,
    students: 1247,
    price: 99.99,
    duration: "12 hours",
    lessons: 24,
    enrolled: true,
    thumbnail: null,
  },
  {
    key: "2",
    id: "CRS002",
    title: "Machine Learning Fundamentals",
    instructor: "Prof. Michael Rodriguez",
    category: "Data Science",
    level: "Intermediate",
    rating: 4.8,
    students: 856,
    price: 149.99,
    duration: "18 hours",
    lessons: 32,
    enrolled: true,
    thumbnail: null,
  },
  {
    key: "3",
    id: "CRS005",
    title: "UI/UX Design Principles",
    instructor: "Emma Wilson",
    category: "Design",
    level: "Intermediate",
    rating: 4.7,
    students: 643,
    price: 119.99,
    duration: "14 hours",
    lessons: 25,
    enrolled: false,
    thumbnail: null,
  },
  {
    key: "4",
    id: "CRS006",
    title: "Data Analysis with Excel",
    instructor: "Maria Garcia",
    category: "Data Science",
    level: "Beginner",
    rating: 4.6,
    students: 1456,
    price: 69.99,
    duration: "9 hours",
    lessons: 18,
    enrolled: false,
    thumbnail: null,
  },
  {
    key: "5",
    id: "CRS007",
    title: "Mobile App Development",
    instructor: "John Smith",
    category: "Programming",
    level: "Advanced",
    rating: 4.5,
    students: 789,
    price: 129.99,
    duration: "20 hours",
    lessons: 35,
    enrolled: false,
    thumbnail: null,
  },
  {
    key: "6",
    id: "CRS008",
    title: "Content Marketing Mastery",
    instructor: "Alex Johnson",
    category: "Marketing",
    level: "Intermediate",
    rating: 4.4,
    students: 532,
    price: 89.99,
    duration: "11 hours",
    lessons: 22,
    enrolled: false,
    thumbnail: null,
  },
];

// Mock course data
export const courseData = {
  CRS001: {
    title: "Advanced React Development",
    instructor: "Dr. Sarah Chen",
    rating: 4.9,
    students: 1247,
    duration: "12 hours",
    progress: 65,
    completedLessons: 16,
    totalLessons: 24,
    description:
      "Master advanced React concepts including hooks, context, performance optimization, and modern patterns. This comprehensive course will take you from intermediate to expert level.",
    curriculum: [
      {
        section: "Getting Started",
        lessons: [
          {
            id: 1,
            title: "Course Introduction",
            duration: "5:30",
            completed: true,
            locked: false,
          },
          {
            id: 2,
            title: "Setting up the Development Environment",
            duration: "12:45",
            completed: true,
            locked: false,
          },
          {
            id: 3,
            title: "React Fundamentals Review",
            duration: "18:20",
            completed: true,
            locked: false,
          },
        ],
      },
      {
        section: "Advanced Hooks",
        lessons: [
          {
            id: 4,
            title: "useEffect Deep Dive",
            duration: "25:15",
            completed: true,
            locked: false,
          },
          {
            id: 5,
            title: "Custom Hooks Patterns",
            duration: "22:30",
            completed: true,
            locked: false,
          },
          {
            id: 6,
            title: "useCallback and useMemo",
            duration: "19:45",
            completed: false,
            locked: false,
          },
        ],
      },
      {
        section: "State Management",
        lessons: [
          {
            id: 7,
            title: "Context API Advanced Patterns",
            duration: "28:10",
            completed: false,
            locked: false,
          },
          {
            id: 8,
            title: "Redux Toolkit Integration",
            duration: "35:20",
            completed: false,
            locked: true,
          },
          {
            id: 9,
            title: "Zustand State Management",
            duration: "24:15",
            completed: false,
            locked: true,
          },
        ],
      },
      {
        section: "Performance Optimization",
        lessons: [
          {
            id: 10,
            title: "React.memo and Optimization",
            duration: "21:30",
            completed: false,
            locked: true,
          },
          {
            id: 11,
            title: "Code Splitting and Lazy Loading",
            duration: "26:45",
            completed: false,
            locked: true,
          },
          {
            id: 12,
            title: "Bundle Analysis",
            duration: "15:20",
            completed: false,
            locked: true,
          },
        ],
      },
    ],
    materials: [
      { name: "Course Slides - Week 1", type: "PDF", size: "2.5 MB" },
      { name: "Source Code - Hooks Examples", type: "ZIP", size: "1.2 MB" },
      { name: "Cheat Sheet - React Patterns", type: "PDF", size: "850 KB" },
      { name: "Assignment - Custom Hook", type: "PDF", size: "450 KB" },
    ],
    notes: [
      {
        id: 1,
        lesson: "useEffect Deep Dive",
        content:
          "Remember: useEffect runs after every render by default. Use dependency array to control when it runs.",
        timestamp: "2024-01-20 14:30",
      },
      {
        id: 2,
        lesson: "Custom Hooks Patterns",
        content:
          'Custom hooks should start with "use" and can call other hooks. Great for reusing stateful logic.',
        timestamp: "2024-01-19 16:45",
      },
    ],
    qna: [
      {
        id: 1,
        question: "When should I use useCallback vs useMemo?",
        answer:
          "Use useCallback for memoizing functions and useMemo for memoizing expensive calculations or objects.",
        author: "Dr. Sarah Chen",
        timestamp: "2024-01-18 10:30",
        likes: 15,
      },
      {
        id: 2,
        question: "How do I prevent unnecessary re-renders?",
        answer:
          "Use React.memo for components, useCallback for functions passed as props, and useMemo for expensive calculations.",
        author: "Student Helper",
        timestamp: "2024-01-17 14:20",
        likes: 8,
      },
    ],
  },
};
